server:
  port: 2469

security:
  basic:
    enable: false
  ignored: /**
  
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  application:
    name: smesh
  cloud:
    config:
      enabled: false

#smesh:
#  service: 
#    name: aws-hello
#    url: https://sg86bqygsk.execute-api.eu-west-2.amazonaws.com/hello
#    selectors: 
#      - address:/aws/hello.*
#      - method:GET
#    requestFilters:
#      - logger:INFO
#      - header:REMOVE:Host
#    responseFilters:
#        - logger:INFO

smesh:
  service: 
    name: fruit-service
    url: http://10.154.1.5:9003/api
    selectors: 
      - address:/number.*
      - method:GET
    requestFilters:
      - logger:INFO
      - header:REMOVE:Host
    responseFilters:
      - logger:INFO
  
  

  
  
